# Generated by Django 4.0.6 on 2022-08-19 02:43

from django.db import migrations, models
import send_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('send_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='bid_price',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='close',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='high',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='low',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='open',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bid_price',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='users',
            name='available_funds',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='users',
            name='blocked_funds',
            field=models.FloatField(validators=[send_data.models.validate_decimals]),
        ),
    ]
